// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo6lkvhiWu6osdNYOs4y6Xi3wiihVZiNY',
    appId: '1:838057731596:web:3f01679cc4c007985f3029',
    messagingSenderId: '838057731596',
    projectId: 'dinda-2b222',
    authDomain: 'dinda-2b222.firebaseapp.com',
    storageBucket: 'dinda-2b222.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmSCuFW083VFfrkKPydWGOajN5dDi9NhQ',
    appId: '1:838057731596:android:01d06d3f6255a11a5f3029',
    messagingSenderId: '838057731596',
    projectId: 'dinda-2b222',
    storageBucket: 'dinda-2b222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwyynXCoXdCrgSipkoVKtYRNYiN5saOjI',
    appId: '1:838057731596:ios:3238f181380e0f595f3029',
    messagingSenderId: '838057731596',
    projectId: 'dinda-2b222',
    storageBucket: 'dinda-2b222.firebasestorage.app',
    iosBundleId: 'com.example.frontEndMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwyynXCoXdCrgSipkoVKtYRNYiN5saOjI',
    appId: '1:838057731596:ios:3238f181380e0f595f3029',
    messagingSenderId: '838057731596',
    projectId: 'dinda-2b222',
    storageBucket: 'dinda-2b222.firebasestorage.app',
    iosBundleId: 'com.example.frontEndMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo6lkvhiWu6osdNYOs4y6Xi3wiihVZiNY',
    appId: '1:838057731596:web:22f63b201cd6ae185f3029',
    messagingSenderId: '838057731596',
    projectId: 'dinda-2b222',
    authDomain: 'dinda-2b222.firebaseapp.com',
    storageBucket: 'dinda-2b222.firebasestorage.app',
  );
}
